spring:
  application:
    name: gRPC-api

#because the certificate is not signed by a thrusted (CA) authority I had to add the certificate here so I can make the TLS work.
#using POSTMAN works without adding the certificate
#addint the server certificate here is needed because the client app checks if the certificate was signed by an CA authority
grpc:
  server:
    port: 6767
#    security:
#      enabled: true
#      certificate-chain: file:src/main/resources/certificate/server.crt
#      private-key: file:src/main/resources/certificate/server.key
  client:
    gRPC-core:
      address: static://localhost:6565
      negotiation-type: TLS
      security:
        trust-cert-collection: file:src/main/resources/certificate/server.crt

auth0:
  clientId:
  clientSecret:
  tokenUri:
  audience:

  clientRegistrationId:
