spring:
  application:
    name: gRPC-core
    # do not save credentials like this in prod!!!!
    #https://vladmihalcea.com/spring-boot-application-properties/
  datasource:
    password: '1234'
    username: 'ginitoru'
    url: jdbc:mysql://localhost:3306/gRPC_test
    hikari:
      minimum-idle: 0 # minimum connections at idle
      maximum-pool-size: 40 # maximum connections to database
      max-lifetime: 900000 # close connection after 10 min (just in case we have a connection failure, the poll will not know the connection was closed, so just to be sure)
      transaction-isolation: TRANSACTION_READ_COMMITTED

     # The auto-commit mode is disabled, and we are going to let Hibernate know about this
     # via the hibernate.connection.provider_disables_autocommit setting. This way, Hibernate
     # can acquire the database connection lazily right before executing a query or prior
     # to flushing the Persistence Context, as opposed to the default behavior, which makes Hibernate
     # acquire the connection right when entering a @Transactional method.
      auto-commit: false

    # statement cashing
      data-source-properties:
        useServerPrepStmts: false
        cachePrepStmts: true
        prepStmtCacheSize: 500
        prepStmtCacheSqlLimit: 1024

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # because I'm to lazy to use a library to show sql queries
    open-in-view: false # disable Open-Session in View anti-pattern
    properties:
      hibernate:
        jdbc:
          time_zone: UTC #save as JDBC
          batch_size: 15 # set the default batch size (recommended size is between 5-30)
        order_inserts: true # for batch inserts
        order_updates: true # for batch updates
        connection:
          provider_disables_autocommit: true # acquire database connection when the first statement is executed and not when the @Transaction begins
        query:
          in_clause_parameter_padding: true
          fail_on_pagination_over_collection_fetch: true
          plan_cache_max_size: 4096
#        dialect: org.hibernate.dialect.MySQLDialect # it will be set as default

grpc:
  server:
    port: 6565
    security:
      enabled: true
      certificate-chain: file:src/main/resources/certificate/server.crt
      private-key: file:src/main/resources/certificate/server.key
#      client-auth: REQUIRE


auth-server:
  url:


