version: '3.8'

services:
#mysql--------------------------------------------------------
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: gRPC_test
      MYSQL_USER: 'ginitoru'
      MYSQL_PASSWORD: '1234'
      MYSQL_ROOT_PASSWORD: '1234'
    volumes:
      - mysql-volume:/var/lib/mysql
    cap_add:
      - SYS_NICE
    ports:
      - '3306:3306'

networks:
  default:

volumes:
  # postgres-volume:
  # mongo-volume:
  # redis-volume:
  mysql-volume:
